# Generated by Django 2.1.7 on 2019-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('_password', models.TextField()),
                ('_passphrase', models.TextField(blank=True, null=True)),
                ('is_sshkey', models.BooleanField(default=False)),
            ],
        ),
    ]
