# Generated by Django 2.1.7 on 2019-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nodes', '0002_node_credentials'),
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='nodes',
            field=models.ManyToManyField(to='nodes.Node'),
        ),
        migrations.AddField(
            model_name='credential',
            name='tags',
            field=models.ManyToManyField(to='nodes.Tag'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='_passphrase',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='_password',
            field=models.BinaryField(),
        ),
    ]
