# Generated by Django 2.1.7 on 2019-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('credentials', '0002_auto_20190216_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='nodes',
            field=models.ManyToManyField(null=True, to='nodes.Node'),
        ),
    ]
