# Generated by Django 2.1.7 on 2019-02-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('credentials', '0003_auto_20190216_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='nodes',
            field=models.ManyToManyField(to='nodes.Node'),
        ),
    ]
