# Generated by Django 2.1.7 on 2019-02-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('hostname', models.TextField()),
                ('site_code', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_edit', models.DateTimeField(null=True)),
                ('autoupdate_enabled', models.BooleanField(null=True)),
                ('autoupdate_branch', models.TextField(null=True)),
                ('firmware_base', models.TextField(null=True)),
                ('firmware_release', models.TextField(null=True)),
                ('model', models.TextField(null=True)),
                ('last_import', models.DateTimeField(auto_now=True)),
                ('first_import', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('is_online', models.BooleanField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('gateway', models.CharField(max_length=12, null=True)),
                ('gateway_nexthop', models.CharField(max_length=12, null=True)),
                ('ipaddress', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(to='nodes.Tag'),
        ),
    ]
